### ISSUE TITLE
Compile error on Linux

### ISSUE THREAD

**Issue by asweet42** [nasa/XPlaneConnect#102]
On compiling the C client for XPlaneConnect, on Linux, I got the following error:

[...]/xplaneConnect/C/src/xplaneConnect.c:125:17: error: storage size of ‘timeout’ isn’t known
  struct timeval timeout;

I resolved this by changing line 49 #include <time.h> to 

#ifdef _WIN32
  #include <time.h>
#else
  #include <sys/time.h>
#endif

That at least compiled on Linux and Windows. If there are configuration steps I didn't do, that would take care of this, please let me know. I didn't try running it.

**Comment by jason-watkins** [comment]
Hi asweet,

Could you tell me what Linux distro and compiler you're using?

**Comment by asweet42** [comment]
Hi Jason,

I'm Adam Sweet from Ames - I expected the note to go to Chris, I emailed
him about it.

but yes, I'm using Debian linux (in a VM actually) with gcc 4.9.2.

Adam

**Comment by teubert** [comment]
Hi Adam, Jason,

A quick search reveals that timeval is defined in sys/time.h,  not time.h, which seems to be what is causing Adam's problem. I'm surprised that this hasn't been an issue earlier! I'll run some tests with the change.

Chris

**Comment by jason-watkins** [comment]
@asweet42 I... should have put that together. In my defense I haven't had coffee yet.

@teubert Yeah, best guess it happened to work on the one setup I used to compile XPC, but not on all Linux setups. I have a feeling sys/time is "more correct" and will work on any *nix system.

**Comment by jason-watkins** [comment]
Fixed in 1dfe7bf.
