### ISSUE TITLE
selectData definition missing from xpc.py

### ISSUE THREAD

**Issue by rkalghatgi** [nasa/XPlaneConnect#108]
Hello,

I'm working in python and trying to select and read data from X-Plane. I would like to use selectData and readData, however the definition for selectData in xpc.py is not present. Should I be using something else?

Thanks,

Roshan

**Comment by jason-watkins** [comment]
readData has never worked very well for us. It's much more reliable to retrieve values by dred.

**Comment by rkalghatgi** [comment]
Yeah after I made this post, I tried out using dref and used the references listed in the X-Plane manual and it worked very easily for me. Thanks!
