### ISSUE TITLE
X-Plane crashes Quick start

### ISSUE THREAD

**Issue by keita-f-sato** [nasa/XPlaneConnect#124]
Hi,
I want to try use XPlaneConnect. 
first, according to quick start, XPlaneConnect was put in specified folder.
after, then you can select aircraft by launching XPlane.
However, after that the background is gray and the cockpit viewpoint is displayed,
but nothing can move.
And the application crashes.
Deleting XPlaneConnect will return to normal.
The system environment is as follows.
OS: Windows10
XPlane-10 64bit steam version

if you have an answer to my problem, I'm happy if you help me.
Thank you for reading my bad English.

**Comment by MichaelRThompson** [comment]
Are you actually sending any commands through XPlaneConnect, or does it just crash on its own?
