### ISSUE TITLE
is it applicable to xplane11???

### ISSUE THREAD

**Issue by SASAWEN** [nasa/XPlaneConnect#133]

**Comment by jason-watkins** [comment]
We have not done very much testing on X-Plane 11, but we expect it to work. Certainly the basic format of DREFs is unchanged. If you run in to any specific problems, please report them and we may be able to fix them.

**Comment by SASAWEN** [comment]
Hi jason,
   I have some problem in Getting Start session...


    Installing the plugin
Binaries for the XPC plugin on all platforms are included in this repository. Installing the plugin is simply a matter of copying a few files. The plugin binaries are located in [XPlaneConnect Repository]\xpcPlugin\XPlaneConnect. Copy this entire folder to the [X-Plane Path]\Resources\plugins folder.

The plugin should now be installed. To verify, run X-Plane, and open the Plugins->Plugin Admin->Enable/Disable menu. You should see an entry named "XPlaneConnect [Version 1.X.X]"


    I have installed Xplane11 and Xplane10, but I can't find "Plugins->Plugin Admin->Enable/Disable menu" in neither Xplane11 nor Xplane10. I am wondering whether there is something wrong during my installing process?

**Comment by jason-watkins** [comment]
Well, I can tell you for sure that XPC works well with X-Plane 10. What is your operating system and OS version?

**Comment by SASAWEN** [comment]
Windows10  :)

**Comment by jason-watkins** [comment]
Alright... next question. Could you confirm that the `X-Plane 10\Resources\plugins` folder exists (presumably so since you should have put the XPC folder there), and list the contents of that folder?

**Comment by SASAWEN** [comment]
yes，already listed in here

**Comment by SASAWEN** [comment]
![_20180718122016](https://user-images.githubusercontent.com/39116457/42859188-0f25ce76-8a85-11e8-8afd-69860f270444.png)
