### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by axita04** [nasa/XPlaneConnect#145]
Platform : Linux
Language : Python
I am repeatedly getting a timeout error while using the getDREFs() method. 
The error can be backtracked to readUDP(). I have increased the timeout in the constructor to 3000, but it still gives me the same error after a few minutes.

**Comment by markaduol** [comment]
I'm having this error as well.

**Comment by TheDigitalDev** [comment]
Same issue with Java version

> `    public HashMap<String, float[]> getDrefs(String[] arr) {
        HashMap<String,float[]> results = new HashMap<>();
        int chunk = 255; // chunk size to divide
        int cSize = arr.length / chunk + 1;

        String[][] chunkedDrefs = new String[cSize][chunk];

        int chunkCounter = 0;
        for(int i = 0; i < cSize; i++){
            chunkedDrefs[i] = (Arrays.copyOfRange(arr, chunkCounter, Math.min(arr.length,chunkCounter+255)));
            chunkCounter = (chunkCounter+255>arr.length) ? arr.length - (arr.length%chunk) : chunkCounter+255;
        }
        for(String[] drefs : chunkedDrefs) {
            try {
                float[][] values = xPlaneConnect.getDREFs(drefs);
                for(int i = 0; i < drefs.length; i++) {
                    results.put(drefs[i],values[i]);
                }
            } catch (IOException e){
                System.out.println("[!] Error fetching DREFs\n" + e);
            }
        }
        return results;
    }
`

Catches the IOException
java.io.IOException: No response received.

**Comment by onionysy** [comment]
Do you fix the problem? I have the same problem with getDREFs().
Can you tell me how do you fix it?
Thank you very much! @axita04 @TheDigitalDev @jason-watkins

**Comment by TheDigitalDev** [comment]
Sorry but why was this closed? Is there something we're missing that was detailed in the docs or... just any answer would be nice

**Comment by jason-watkins** [comment]
In short because timeouts really have nothing to do with XPlane Connect and there's no useful advice I can give. I suppose I should add a section to the Readme or Wiki that explains that as clearly and thoroughly as possible.

**Comment by axita04** [comment]
I kept increasing the timeout value in the __init__() definition until I
stopped getting the error.

**Comment by YingxiaoKong** [comment]
I also got the timeout error when using client.readUDP(), anyone has any idea?

**Comment by sanderdatema** [comment]
Too many requests per second will get you a timeout (if you didn't just do one request only). I build in a 'throttle' to maximize the amount to max 10/sec.

**Comment by YingxiaoKong** [comment]
Thanks for your reply. I didn’t do anything and suddenly the problem disappeared. By the way, could you share with me more information about what you mean by ‘throttle’? Is this a UDP management command?


在 2020年8月6日，上午1:21，Sander Datema <notifications@github.com> 写道：

﻿

Too many requests per second will get you a timeout (if you didn't just do one request only). I build in a 'throttle' to maximize the amount to max 10/sec.
