### ISSUE TITLE
Sending "commands" #134

### ISSUE THREAD

**Issue by yvesbbbb** [nasa/XPlaneConnect#150]
Bonjour Jason,

@jason-watkins
"Here is a Windows/Linux build of the plugin from the PR branch....."

Tip on no file ! :-(

https://github.com/nasa/XPlaneConnect/issues/134

Thank you for your code, very useful

**Comment by yvesbbbb** [comment]
It's Ok, I compiled the code.

**Comment by mupok** [comment]
Hi, can you share the plugin please?

**Comment by yvesbbbb** [comment]
I compiled the code with Visual Studio Communauty 2017 from this branch
https://github.com/rthaenert/XPlaneConnect.

It's working perfectly !

The compiled 64 bits plugin for windows
https://drive.google.com/file/d/1z6f4FbqaA3Nz_1GZ9EPv6S6dVs-qa7h6/view?usp=sharing

Have a nice day !

**Comment by mupok** [comment]
Thank you very much!
