### ISSUE TITLE
Questions About Validating Sim Data

### ISSUE THREAD

**Issue by dwp7kp** [nasa/XPlaneConnect#164]
Hey

I'm working on a project where we are trying to create a simulation of the X-59 plane inside of X-Plane. We have some simulation data and we are trying to compare how our plane flies to the actual sim.

Currently we are trying to feed X-Plane some initial conditions, but we have not been successful. X-Plane either overwrites the manual deflections we are feeding it or there is lag created when we try to feed it stick inputs and record deflections at the same time. I was wondering if your team had experimented with anything like this and if you had any suggestions.

**Comment by jason-watkins** [comment]
Hi Daniel,

Unfortunately this is a pretty common comment I receive from people using X-Plane Connect and there's not a lot I can do about it on my end. The plugin on the X-Plane side of XPC is really a pretty thin wrapper around the X-Plane SDK and I don't have any control over what happens inside X-Plane after I hand of the values to it.

If you want to follow up in more detail via email, I'd be happy to take a look at your code or discuss what you're doing over the phone to see if there are any specific issues that I can help with. My email is in my profile.

Regards,
Jason
