### ISSUE TITLE
how to use XPC

### ISSUE THREAD

**Issue by Taruio** [nasa/XPlaneConnect#165]
Hello,
In the guide of XPC, I found that     ‘ The plugin binaries are located in [XPlaneConnect Repository]\xpcPlugin\XPlaneConnect. Copy this entire folder to ......’    , but I can not find the 'XPlaneConnect' folder in the '[XPlaneConnect Repository]\xpcPlugin\' 
Best wishes

**Comment by jason-watkins** [comment]
Hi Taruio,

Thanks for pointing this out. I've removed the binaries from the repo because they have a habit of being out of date. You can find the binaries for the latest release on the [releases](https://github.com/nasa/XPlaneConnect/releases) page. I'll update the docs to reflect that as well.
