### ISSUE TITLE
Linker error with Visual Studio 2017

### ISSUE THREAD

**Issue by yvesbbbb** [nasa/XPlaneConnect#166]
Hi Jason,
The compilation is Ok  but the linkage display this error !?

error LNK2001: unresolved external symbol "public: void __cdecl XPC::Timer::stop(void)" (?error LNK2001: unresolved external symbol "public: void __cdecl XPC::Timer::start
....
1>..\XPlaneConnect\64\win.xpl : fatal error LNK1120: 2 unresolved externals
1>Done building project "xpcPlugin.vcxproj" -- FAILED.

Have a nice day,

Thank you

**Comment by jason-watkins** [comment]
Thanks for the report. I’m out of town this weekend so i can’t verify this right now. @JanC, am I remembering right that you added the Timer as part of the Beacon code? Do you have any ideas?

**Comment by yvesbbbb** [comment]
Take your time, it's not a rush.
Thank you

**Comment by JanC** [comment]
Hi,
yes the `Timer` class was added recently. I’ll try to reproduce the error and will report back.

**Comment by JanC** [comment]
@yvesbbbb could you please give me a link where I can download MS Visual Studio 2017? All the links I found on https://visualstudio.microsoft.com/ point to Visual Studio 2019.

Also which configuration (`Debug` or `Release`)  and which platform (`Win32` or `x64`) do you build when you get this error?

**Comment by yvesbbbb** [comment]
Hi JanC,

I used the release X64 configuration with Windows 10 and the lastest update of VS2017

Thank you,

Yves

**Comment by JanC** [comment]
So we have the same setup but your fails. Could you please post en entire build log?

**Comment by yvesbbbb** [comment]
Hi JanC,

The complete log is the attach file.

Thank you for your time !

[Yves]
[LinkErrors.txt](https://github.com/nasa/XPlaneConnect/files/3468911/LinkErrors.txt)

**Comment by JanC** [comment]
Could you double check that
- you have a unmodified version of the repo on the `master` branch
- the `Timer.cpp` file is correctly in the ` Source Files` tree in Visual Studio?

![xcp](https://user-images.githubusercontent.com/707703/62488557-d534ef80-b7c4-11e9-959a-9d0b2e7e9656.JPG)

**Comment by yvesbbbb** [comment]
Exactly the same ;-)
![LinkErrors](https://user-images.githubusercontent.com/47287575/62489486-d51cfb80-b794-11e9-9892-8bdbc8799f7a.png)

**Comment by JanC** [comment]
```
1>x64\Release\Timer.obj : warning LNK4042: object specified more than once; extras ignored
```
I also see this line in the build log but it's suspicious. I noticed that the Item Type of `Timer.h` is set to `C/C++ compiler` while it should be `C/C++ header`.

Could you right click on `Timer.h` in VS,  select `Properties > General`  and change the `Item Type` to `C/C++ header`. Then clean and build again.


![xcp2](https://user-images.githubusercontent.com/707703/62491096-52636300-b7cb-11e9-953b-84906568ebf4.JPG)

**Comment by yvesbbbb** [comment]
Bingo !!!
You got it !!

1>Generating code
1>Finished generating code
1>xpcPlugin.vcxproj -> E:\Mes documents\FS\Xplane\GIT\XPlaneConnect-master\xpcPlugin\xpcPlugin\..\XPlaneConnect\64\win.xpl
1>Done building project "xpcPlugin.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Many thanks !!   ;-) ;-)

**Comment by JanC** [comment]
de rien ;)

Great! I created a pull request to fix this.

**Comment by jason-watkins** [comment]
Thanks to both of you for getting this figured out. I've merged the fix into develop. I'll push out a new RC tonight to update master.

The mysteries of Visual Studio are a long standing frustration to us all. I'm not happy about it, but I've basically given up trying to understand *why* Visual Studio does anything.
