### ISSUE TITLE
Error LNK2019	unresolved external symbol _openUDP referenced in function _main

### ISSUE THREAD

**Issue by Andrew738** [nasa/XPlaneConnect#174]
Hi,

When i try to build the following i get a error "LNK2019	unresolved external symbol _openUDP referenced in function _main". I have included the xplaneConnect.h file

#include <iostream>
#include "xplaneConnect.h"

int main()
{
	XPCSocket sock = openUDP("127.0.0.1");

	// Get the status of the gear handle
	const char* dref = "sim/cockpit/switches/gear_handle_status";
	float value = 0.0F;
	int size = 1;
	if (getDREF(sock, dref, &value, &size) < 0)
	{
		printf("And error occured.");
	}
	else
	{
		printf("The gear handle status is %f.", value);
	}

	closeUDP(sock);
}

**Comment by jason-watkins** [comment]
Hi Andrew,

How are you compiling the code? It sounds like you are only compiling the main file. You need to compile both your main file and the xplaneConnect.c file and link both of them. The exact way that you do this depends on what build tools you're using.

**Comment by jason-watkins** [comment]
Also, please open a new issue for any questions you have (as you've done here) rather than commenting on an unrelated issue. I've deleted your other comment on #173, but feel free to re-post it as its own issue.

**Comment by Andrew738** [comment]
Hi Jason, 

Will do. 

Thanks, i think i forgot the xplaneConnect.c file. Just new to visual studio 2019. Programmed always with xcode ;-)

**Comment by Andrew738** [comment]
Works and you can close the issue ;-)

**Comment by jason-watkins** [comment]
Glad to hear you were able to figure it out.
