### ISSUE TITLE
Error using readDATA() from Python3

### ISSUE THREAD

**Issue by ishit07** [nasa/XPlaneConnect#176]
Hi, I am using Python3 code to read the whole UDP data from x-plane11 simulator. With the MonitorExample, I am able to fetch the posi and ctrl data but when I am using readDATA() function I am unable to get the data. The screenshot of the error I have attached below.
If you can help me with 2 things 
1. How to use readDATA function.
2. In the getPOSI function I have seen you have passed a GETP keyword and for getCTRL function you have passed GETC so is there a way to find out these keywords so that I can pass these keywords and get the data out for other properties as well.

<img width="1430" alt="Screen Shot 2019-08-30 at 12 15 01 PM" src="https://user-images.githubusercontent.com/47466428/64036206-a2aab800-cb20-11e9-8289-f7aba11fd279.png">
<img width="596" alt="Screen Shot 2019-08-30 at 12 22 46 PM" src="https://user-images.githubusercontent.com/47466428/64036434-311f3980-cb21-11e9-8b5c-cd1b4358a2b7.png">

**Comment by jason-watkins** [comment]
The readDATA function is, frankly not well supported. I don't see any reason why it would time out. The plugin log would be helpful to figure out why it's not responding.

You can find the network protocol specification [here](https://github.com/nasa/XPlaneConnect/wiki/Network-Information).
