### ISSUE TITLE
To get local v

### ISSUE THREAD

**Issue by onionysy** [nasa/XPlaneConnect#179]
thanks for your open code. But when I try to get local_vx through DREF with python 
(vv=client.getDREF("sim/flightmodel/position/local_vx")[0])
it raise 

`Traceback (most recent call last):
  File "/basicExample.py", line 524, in <module>
    ex(ddpg,st,ac)
  File "/basicExample.py", line 30, in ex
    vv=client.getDREF("sim/flightmodel/position/local_vx")[0]
  File "\xpc.py", line 324, in getDREF
    return self.getDREFs([dref])[0]
  File "\xpc.py", line 343, in getDREFs
    buffer = self.readUDP()
  File "\xpc.py", line 70, in readUDP
    return self.socket.recv(16384)
socket.timeout: timed out`

I want to fix it, and hope you can give me some advice.
thank you

**Comment by jason-watkins** [comment]
The error message tells you that the socket timed out. That doesn't have anything to do with XPlaneConnect. You need to fix whatever issue is causing the timeout or make the timeout window longer.
