### ISSUE TITLE
sendPOSI always sets gear to 0 with some clients

### ISSUE THREAD

**Issue by dfremont** [nasa/XPlaneConnect#184]
In XPlaneConnect 1.3, the `sendPOSI` command in the Python 3 client always sets the gear to 0 (up) rather than the desired value. Jason tracked the bug down to [this line](https://github.com/nasa/XPlaneConnect/blob/9f57f7d61fcbcc80eff5477089c1124be2e0536f/xpcPlugin/MessageHandlers.cpp#L583), which doesn't correctly handle clients which use POSI messages with 32-bit precision for latitude/longitude/elevation.

N.B. We found this problem when we upgraded to XPC 1.3 and `sendCTRL` no longer caused the nose wheel of the plane to turn (only the rudder). The issue turned out to be that we were calling `sendPOSI` first, which set the dataref `sim/aircraft/parts/acf_gear_deploy` to 0 because of this bug, which in turn causes the yoke input to no longer turn the wheel.

**Comment by jason-watkins** [comment]
Fixed in #182.

We added support for 64 bit lat/lon/alt to the POSI message quite a while ago in `develop`, but just merged the change in to `master` for the latest set of release candidates, which surfaced this bug.

Thanks @dfremont for the report.
