### ISSUE TITLE
New Python Programmer trouble with sendCOMM

### ISSUE THREAD

**Issue by LionheartUK** [nasa/XPlaneConnect#195]
Hi all,

Need a bit of help with the sendCOMM function. I read that the latest release client does not have this command in the xpc.py or the compiled plugin. Im using python to communicate between and arduino and X-Plane, I have managed to get datarefs in and out with no issues at all but when it comes to the sendCOMM command im hitting a wall. I see the since rc2 that the command was added but I cant see it in any of the xpc.py files or the plugin.

Does anyone have a compiled plugin that accepts sendCOMM commands and an xpc.py with the sendCOMM command in it?

Thank you.

Regards

Richard

**Comment by epaton2** [comment]
I'm working on compiling a plugin with sendCOMM added.
Eric

**Comment by jason-watkins** [comment]
See #197 and #219, we have re-added the missing code.
