### ISSUE TITLE
Error with readDATA and getDREFs in Matlab 2019b

### ISSUE THREAD

**Issue by smzelman** [nasa/XPlaneConnect#207]
I am having some trouble with getDREFs in Matlab R2019b.

I get the following error after opening a UDP socket on port 49009:

    Error using XPlaneConnect.getDREFs (line 36)
    Java exception occurred:
    java.io.IOException: No response received.
    
    at
        gov.nasa.xpc.XPlaneConnect.getDREFs(XPlaneConnect.java:299)

I am also having trouble with readDATA which gives me this error:

    Error using XPlaneConnect.readDATA (line 49)
    Java exception occurred:
    java.lang.IndexOutOfBoundsException: 5
    
    at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139)
    
    at
        gov.nasa.xpc.XPlaneConnect.readData(XPlaneConnect.java:685)

I have enabled the plugin in X-Plane and I am sending General Data Output to 127.0.0.1.

Some of the other functions in Example.m will evaluate without error like sendPOSI, pauseSim, etc. However I am not sure these commands are actually seen by X-Plane.

Log files:
[XPCLog.txt](https://github.com/nasa/XPlaneConnect/files/4674556/XPCLog.txt)
[Log.txt](https://github.com/nasa/XPlaneConnect/files/4674557/Log.txt)

Does anyone have troubleshoot advice?
Thanks

**Comment by CharonP1** [comment]
Hello!
I encountered the same problem as you when using XPC in MATLAB2021b
When my xpPort uses a port other than 49009, I get the following error:
```
Error using XPlaneConnect.getDREFs (line 36)
Java exception occurred:
java.io.IOException: No response received.
	at gov.nasa.xpc.XPlaneConnect.getDREFs(XPlaneConnect.java:299)
```
When I use result = readDATA();, I also get the following error:
xpc readDATA Java exception occurred: 
```
java.lang.IndexOutOfBoundsException: 5 	

at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139) 	

at 
      gov.nasa.xpc.XPlaneConnect.readData(XPlaneConnect.java:678)
```
How did you solve the above problem? Thank you!
