### ISSUE TITLE
Send coordinates and altitude in real time to control the flight path of the aircraft

### ISSUE THREAD

**Issue by shanccshuirr** [nasa/XPlaneConnect#209]
Use sendPOSI() and sendWYPT()

Any difference?

**Comment by jason-watkins** [comment]
You can read what [sendPOSI](https://github.com/nasa/XPlaneConnect/wiki/sendPOSI) does and what [sendWYPT](https://github.com/nasa/XPlaneConnect/wiki/sendWYPT) does. sendPOSI sets the position of the aircraft. sendWYPT just draws a visual indicator.
