### ISSUE TITLE
Playback Executable

### ISSUE THREAD

**Issue by teubert** [nasa/XPlaneConnect#21]
Create an executable to run a playback file. This executable will read a playback file and set the aircraft position/orientation as indicated in the playback file.

Example Operation:
./runPlayback pb1.xpc

Example Playback File pb1.xpc:
Time, Aircraft, Lat, Lon, Alt, Roll, Pitch, Yaw
0, 1, 34.5, 67.2, 500, 0, 0, 0
0.1, 1, 34.5001, 67.2, 500, 0, 0, 0

**Comment by jason-watkins** [comment]
After discussing this, it seems like this would be better served by a fully client side implementation. #70 and #74 will demonstrate how similar functionality might be accomplished.
