### ISSUE TITLE
My data is obtained every 15ms. I try to send this data to xplane11 model every 15ms, using sendPOSI(), but the aircraft is shaking. According to experience, because the model's own flight is not disconnected, the data I send makes the aircraft switch between the two modes. Please ask me how I solve this problem？

### ISSUE THREAD

**Issue by shanccshuirr** [nasa/XPlaneConnect#211]

**Comment by jason-watkins** [comment]
Asking questions entirely in the title of an issue with no further description is not appropriate. I suggest reading [this page](https://mattgemmell.com/what-have-you-tried) for some suggestions on how to ask questions in a constructive way.
