### ISSUE TITLE
With model flight disabled, there is no change using the sendctrl() flaps

### ISSUE THREAD

**Issue by shanccshuirr** [nasa/XPlaneConnect#213]
In the case of model flight prohibition, the aileron and tail using sendctrl () have changes, but the flap has no change, but the flap and rudder surface have changes when the model flight allows. Because sendposi() is used to change the position of the aircraft, so to disable the model flight, please ask how to change the flap when the model flight is disabled, thank you

**Comment by jason-watkins** [comment]
Unfortunately there are some limitations in X-Plane that aren't easy to work around. This is one of those times.

**Comment by shanccshuirr** [comment]
Thank you for your reply. I will try my best to find a way to refuse
