### ISSUE TITLE
Is it possible to send one part of an array?

### ISSUE THREAD

**Issue by sanderdatema** [nasa/XPlaneConnect#214]
Quite a few datarefs are arrays. You can only request the whole array (or can you?) and you can only send back the whole array. So if you want to change only one item, you need to get the current array first, change one item and send it back.

Is there another way?

**Comment by jason-watkins** [comment]
You are correct about the current plugin functionality. The X-Plane SDK does support getting and setting parts of the array (e.g. [XPLMGetDatavf](http://www.xsquawkbox.net/xpsdk/mediawiki/XPLMGetDatavf), so it should be fairly easy to add new commands that take an offset and count. Pull requests are always welcome!

**Comment by sanderdatema** [comment]
Thanks, but I'm afraid I lack the knowledge to be of any help...
