### ISSUE TITLE
Issue with FBW aircraft

### ISSUE THREAD

**Issue by DheerendraTomar** [nasa/XPlaneConnect#220]
Hi all,

I am experiencing issue while sending control commands to Flight Factor A320 ultimate version. The aircraft is not responding to the commands which I send through sendCTRL. While the xpcLog file says send successful and the dataref also changes but it doesn't affect the aircraft. AutoPilot and AutoThrust are off. Is this because of FBW system of the aircraft?

Thanks,

**Comment by jason-watkins** [comment]
This is probably a better question for the aircraft maker. I don't really have any idea what they're doing or what FBW is, but I would guess that your supposition is likely. It's possible that the FBW system has its own data refs that you could set instead to accomplish the same result.
