### ISSUE TITLE
Waypoints not visible in VR and when using Vulkan engine

### ISSUE THREAD

**Issue by krao-MIT** [nasa/XPlaneConnect#232]
I'm using the sendWYPT function to create waypoints in the simulation. I'm also using the HTC Vive to fly in a simulated VR environment. However, it seems like the waypoints are only appearing in one lens (left eye). The picture attached is captured using StudioOBS screen capture and the waypoints are only visible on the left side. 

It also seems like in the latest version of XPlan11 (11.50) that uses the Vulkan graphics engine, the way points don't appear at all. Have to revert to the OpenGL rendering for the waypoints to appear. 

![Waypoint in One Lens](https://user-images.githubusercontent.com/71723736/93916262-412f2b80-fcd7-11ea-9884-986d48a37c5f.png)

**Comment by jason-watkins** [comment]
The waypoints are drawn using raw `gl` calls, so not too surprising that it doesn't work in Vulkan. Not something I have the time or the knowledge to fix right away unfortunately.

As for drawing on only one screen, again I don't really know what's going on, and my guess is that it has a lot to do with the aforementioned fact that I'm using raw `gl` calls to do the drawing. I would probably need better drawing support from the XPLM API to fix this one.
