### ISSUE TITLE
Sending commands to X-plane

### ISSUE THREAD

**Issue by neusat** [nasa/XPlaneConnect#233]
Is it possible ti send commands to x-plane via XPlaneConnect? Like landing lights on or off, or activate autopilot, battery on, engine start, etc.

http://siminnovations.com/xplane/command/index.php

**Comment by afefer** [comment]
The plugin currently has an operation, "COMM", to momentarily trigger an X-Plane command. I've also just [submitted a pull request](https://github.com/nasa/XPlaneConnect/pull/234) to add two new operations (BCOM, ECOM) for independently beginning and ending X-Plane commands.

**Comment by neusat** [comment]
Dear, thank you for your reply, I cannot find COMM manual operation on Wiki

https://github.com/nasa/XPlaneConnect/wiki/XPC-Client-Reference

How can I use it to send any command to Xplane?

https://www.siminnovations.com/xplane/command/

**Comment by ICURRY-JHT** [comment]
I cannot find COMM either！！

**Comment by sanderdatema** [comment]
My PR #251 was merged in the develop branch. It has the sendCOMM option.
