### ISSUE TITLE
Indicator that rendering graphics is complete?

### ISSUE THREAD

**Issue by Yaseen787** [nasa/XPlaneConnect#246]
I working on a project that includes spawning the aircraft at a certain position, then taking a screenshot of what is seen by the nose of the aircraft (Forward with no display view). This process will be automated by a MATLAB script as it will be done thousands of times automatically. I noticed that there is a gap between setting the position using the sendPOSI() function and actually having the new image rendered on the screen. Oh, and btw, the simulation is paused the whole time because I'm only interested in the images. So what happens is that when I take a screenshot, most likely the image is not yet rendered and I end up taking a shot of the view before the sendPOSI() command, which is not what I want. I could solve this by just placing a delay between the two operations, but I was wondering if there is a way to read that the rendering operation is complete programmatically.

**Comment by epaton2** [comment]
You could set up a getDREF function in a loop and wait for a valid response to come back  (i.e. check the exception handling for this function, it will return a negative value)  A good dataref to check is network_time, but any dataref will do.
