### ISSUE TITLE
Require higher precision for Latitude / Longitude data

### ISSUE THREAD

**Issue by epaton2** [nasa/XPlaneConnect#248]
Looks like this feature was added already.  I was looking at an older version of the code.  Sorry.  The moderator can delete this.

**Comment by epaton2** [comment]
Looks like this feature was added already. I was looking at an older version of the code. Sorry. The moderator can delete this.

**Comment by donfung** [comment]
Could you please point me to where you explicitly see that doubles are accepted? I am still under the impression that the plugin only allows single type values for lat lon.
