### ISSUE TITLE
MonitorExample.m unable to connect to XPlane 11 [Windows 10]

### ISSUE THREAD

**Issue by donfung** [nasa/XPlaneConnect#249]
When I run MonitorExample.m In MATLAB, I'm getting the error "java.io.IOException: No response received.".
![image](https://user-images.githubusercontent.com/17075612/109450967-276ddf00-7a01-11eb-94db-982a07365263.png)

I get the same error when trying to run Example.m as well.

I do have the XPlaneConnect plugin enabled in the Plugin Admin: 
![image](https://user-images.githubusercontent.com/17075612/109450667-4f107780-7a00-11eb-8978-6ad4f48b692b.png)

I have tried several different port numbers but none work -- all produce the same error message.
![image](https://user-images.githubusercontent.com/17075612/109450863-d2ca6400-7a00-11eb-811c-0912076c8810.png)

Here are the relevant settings in the "Network" tab in XP11:
![image](https://user-images.githubusercontent.com/17075612/109450749-8ed75f00-7a00-11eb-8de6-38243d4f8bf9.png)
![image](https://user-images.githubusercontent.com/17075612/109450772-9991f400-7a00-11eb-8ba7-7a6f9fa24dc1.png)

Here are the "Network Configuration" settings in the "Data Output" tab:
![image](https://user-images.githubusercontent.com/17075612/109450782-a1ea2f00-7a00-11eb-8a5f-875c0bba88f7.png)

I am using Windows 10.  

Thanks in advanced.

**Comment by donfung** [comment]
Solved. The port definition in xpcPlugin.cpp (line 77) did not match the port number in the Network settings. Changing line 77 from 49009 to `#define RECVPORT 49000` solved the issue.

**Comment by steagnas** [comment]
Hi donfung. 
Same problem for me.
I did not get how did you solve. I am not able to access _xpcPlugin.cpp_ . Could you please tell me how did you access it, in order to modify liine 77?
Thx

**Comment by donfung** [comment]
Can you please show a screenshot of the errors you're getting? I must be honest it's been awhile since I last touched XPC

**Comment by steagnas** [comment]
![image](https://user-images.githubusercontent.com/93582167/140040067-99d2447d-c0f2-4a09-98ba-8477ce7b0913.png)
 That is. 

I have also noticed that on openUDP.m on line 27 you can modify a port number, but I honestly don't know which is and why.
![image](https://user-images.githubusercontent.com/93582167/140040357-aaebcc84-13be-4019-814b-eb97bd32fb39.png)


Thanks!
