### ISSUE TITLE
Getting airport info such as Runway, Gate number

### ISSUE THREAD

**Issue by VahidNZ** [nasa/XPlaneConnect#252]
Is there any way to getting airport data like the getDREF method?
In this case, I'm using Python and I've no problem getting the aircraft section but I don't know how is it possible to get the airport section.

**Comment by jason-watkins** [comment]
The [XPLMNavication|https://developer.x-plane.com/sdk/XPLMNavigation/] API provides a mechanism for getting airport locations, but not any more detailed information. In any case, XPC does not currently expose this API to clients.

I would be more than happy to look at a PR adding support for XPLMNavigation to the plugin, but it's not something I have time to tackle myself.
