### ISSUE TITLE
Failed to Bind Socket (Error code 10048)

### ISSUE THREAD

**Issue by fpaetzold** [nasa/XPlaneConnect#257]
[XPCLog.txt](https://github.com/nasa/XPlaneConnect/files/6949335/XPCLog.txt)

Hello dear XPC Team,

I have a small problem: I am using a Java program, to connect a CDU to X-Plane. This works totally fine on my other pc, that has X-Plane installed. But on my main pc, with xplane to, it doesn't work. My java program works fine on both pc's, but i think that the X-Plane plugin doesn't work on my main pc. I am pretty sure, that my program works, because it sends data to other pcs just fine.
I am using ports 49009 and 49008.

Thank you in advance!
Best regards

**Comment by jason-watkins** [comment]
Unfortunately this isn't really something that falls within the scope of the plugin. There's just no way for me to debug the issue remotely.
