### ISSUE TITLE
Unable to set sim/weather

### ISSUE THREAD

**Issue by krao-MIT** [nasa/XPlaneConnect#272]
I'm using Windows 10, Matlab 2021a, and XP11 Version 11.55 (OpenGL).
I'm trying to change aspects about the simulated weather using XPC. For example:

`disp('Setting up Simulation');`
`Socket = openUDP('127.0.0.1', 49009);`

`sendDREFs( {'sim/weather/wind_speed_kt'} , single(5) , Socket) % <- Doesn't work`
`result = getDREFs('sim/weather/wind_speed_kt', Socket)`

I can change the weather using the GUI in XP11 and I can read the resulting weather based on those changes from the GUI. But I can't seem to make those same changes from XPC. Documentation online states that the variables are "Writeable" (https://developer.x-plane.com/datarefs/). 

Any help in determining how to manipulate weather using XPC would be appreciated.

**Comment by AlvaroSierra** [comment]
X-Plane 11 does weather in layers so I recommend you edit these layers individually. For this use the DREFs with a `[0]`, `[1]` or `[2]` at the end of the property and then you can define the speed, direction and **altitude** (note that if you want it to be acting on the aircraft it must be set at the same altitude).

In your case you would use the `sim/weather/wind_speed_kt[0]` DREF
