### ISSUE TITLE
Command horizontal and vertical throttles

### ISSUE THREAD

**Issue by IanOMHiggins** [nasa/XPlaneConnect#308]
Hello,

I wish to fly the BETA eVTOL while manually control the vertical throttle with python3. This can be done with a joystick, but I see no writable dataref for this. I could control each propeller with a quadrotor dynamics controller, but I would ideally like to only alter the "Throttle Vertical" just like the joystick can do. Is this possible?

Thanks
Ian

**Comment by YovanDharwal** [comment]
Hi @IanOMHiggins   you can use ''sim/cockpit2/engine/actuators/throttle_ratio_all '' to send throttle command one by one. You can define number of motors  throttleRatios[0] = 0.5; // 
// 			throttleRatios[1] = 0.5; 
// 			throttleRatios[2] = 0.1; 
// 			throttleRatios[3] = 0.1; 
0 for 1st motor and so on. Are you able to give throttle to your VTOL motors manually using joystick??

**Comment by IanOMHiggins** [comment]
Hi, when I said 'manually', I actually meant 'through code' (I am using joystick input to inform my python api calls, bypassing xplane's joystick reader).

Your answer is exactly what I was looking for! (well actually I used 'sim/cockpit2/engine/actuators/throttle_ratio' instead of 'sim/cockpit2/engine/actuators/throttle_ratio_all'). Interestingly, the 'sim/cockpit2/engine/actuators/throttle_ratio' DREF has four separate values for "vertical throttle", but they are always identical, even when the four engines are different speeds (due to roll/pitch commands, etc). Setting all four at once to the same value still allows the stick commands to provide roll/pitch moments, which is the exact behavior I desire. Thanks very much!

**Comment by YovanDharwal** [comment]
if values are identical that means its just for lift throttle(if you know the flight dynamics you will understand)
