### ISSUE TITLE
Reading arrays larger than 255 elements 

### ISSUE THREAD

**Issue by HemuManju** [nasa/XPlaneConnect#311]
Hi Team,

I hope this message finds you well. I've encountered an issue while reading the `sim/joystick/joystick_button_values` through XPC. Currently, the array size exceeds 255 elements.

From my understanding, XPC imposes a limit of 255 on the data read through DREFs. Given this limitation, I'm exploring potential solutions or workarounds to access the complete joystick button array.

Is there a known method or configuration to increase this limit imposed by XPC?

Any insights or guidance on this matter would be greatly appreciated. Thank you in advance for your time and assistance.

**Comment by AlvaroSierra** [comment]
Hi, I recommend you have a look at #277 which looks further into array DREFs.

**Comment by shiroinekotfs** [comment]
If this issue is solved, should it be closed?

**Comment by HemuManju** [comment]
I am still unable to read array values larger than 255. I did a little digging and found that [MessageHandlers.cpp](https://github.com/nasa/XPlaneConnect/blob/master/xpcPlugin/MessageHandlers.cpp) limits all arrays to 255 elements. Is there a reason for this? And how can I change this limit? Any help is greatly appreciated.

**Comment by AlvaroSierra** [comment]
Related to #146

**Comment by HemuManju** [comment]
PR #270 address this issue. I am able to read an array more than 255 elements. I am closing this issue.
