### ISSUE TITLE
Add datarefs for multiplayer global position

### ISSUE THREAD

**Issue by jason-watkins** [nasa/XPlaneConnect#62]

**Comment by jason-watkins** [comment]
Found them. They were just hiding under a different section than I expected. For future reference:

`sim/multiplayer/position/planeN_lat`
`sim/multiplayer/position/planeN_lon`
`sim/multiplayer/position/planeN_el`

**Comment by teubert** [comment]
Great! I knew they had to be somewhere!


On Apr 29, 2015, at 10:50 AM, Jason Watkins <notifications@github.com<mailto:notifications@github.com>> wrote:


Found them. They were just hiding under a different section than I expected. For future reference:

sim/multiplayer/position/planeN_lat
sim/multiplayer/position/planeN_lon
sim/multiplayer/position/planeN_el
