### ISSUE TITLE
Determine java architecture 

### ISSUE THREAD

**Issue by teubert** [nasa/XPlaneConnect#7]

**Comment by jason-watkins** [comment]
Basic implementation [here](https://github.com/jason-watkins/XPlaneConnect/tree/feature/java). There are some function in MATLAB that are not currently tested. Those haven't been included in the Java client yet. The Java integration tests currently cover everything covered by their MATLAB/C counterparts, as well as some additional parameter verification that is made much easier by Java's type system.
