### ISSUE TITLE
Extra line from waypoint

### ISSUE THREAD

**Issue by teubert** [nasa/XPlaneConnect#73]
When running the MATLAB test scripts on mac, an extra red line is coming from the waypoint immediately in front of the vehicle (see screen shot). This line goes into the ground at a steep angle.

![screen shot 2015-05-14 at 12 48 53 pm](https://cloud.githubusercontent.com/assets/8226781/7642328/fa79e288-fa44-11e4-99ad-f489b3eb4dda.png)

**Comment by jason-watkins** [comment]
Can't reproduce on Windows. I suspect that the issue lies in a difference in the Mac and Windows OpenGL implementations.

**Comment by teubert** [comment]
I cannot replicate the three line problem, but after further investigation I have found that 1. The second line only occurs once the test scripts have been run twice. and 2) The line ends at waypoint1 (see attached image)

![screen shot 2015-05-14 at 2 52 03 pm](https://cloud.githubusercontent.com/assets/8226781/7642879/6f4f11ba-fa49-11e4-9558-2d7c5f1db1c1.png)

**Comment by jason-watkins** [comment]
So far, we haven't been able to reproduce this a second time.
