### ISSUE TITLE
Documentation correction: sendCTRL throttle range should be [0,1]

### ISSUE THREAD

**Issue by TurboTiger** [nasa/XPlaneConnect#81]
In the documentation for sendCTRL, the throttle range is given as [-1,1].  The correct range is [0,1], as per the X-Plane dataref list: http://www.xsquawkbox.net/xpsdk/docs/DataRefs.html

In testing with the latest beta (10.40r1), X-plane will happily accept out-of-range values, however, the throttle lever will then move out of its normal track in the 3D cockpit view. :)

Cheers!

**Comment by teubert** [comment]
Good catch! Thanks for letting us know. I've fixed this in the documentation.
