### ISSUE TITLE
maintainer ?

### ISSUE THREAD

**Issue by tony-pelton** [nasa/XPlaneConnect#98]
i tried to use the e-mail address from the README to send a mail about the project and a possible pull request i would generate, and it bounced. sent to Chris. is he still maintainer ? is anyone a maintainer ?

**Comment by jason-watkins** [comment]
Hi Tony,

Chris and I both still actively maintain X-Plane Connect as our other duties allow. It looks like there was a typo in the readme, which I've just fixed.

RE your pull request, you can post here or send email me at jason-watkins@outlook.com and/or Chris at christopher.a.teubert@nasa.gov. Emailing both of us is most likely to get you a quick response.

Thanks,
Jason
